apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cell-sa-central-01

resources:
  - ../../base

configMapGenerator:
  - name: cell-config
    literals:
      - cell.id=cell-sa-central-01
      - jurisdiction.code=SA
      - jurisdiction.name="Kingdom of Saudi Arabia"
      - residency.policy=SDAIA_PDPL_COMPLIANT
      - default.currency=SAR
      - default.locale=ar-SA
      - tax.authority=ZATCA
      - safety.regulator=SASP

patches:
  - target:
      kind: Deployment
      name: integin-server
    patch: |-
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          topology.kubernetes.io/region: me-central-1
          integin.com/sovereign-cell: cell-sa-central-01
          integin.com/jurisdiction: SA
