BEGIN;
DROP POLICY IF EXISTS export_template_tenant_isolation ON export_template;
DROP POLICY IF EXISTS csv_export_job_tenant_isolation ON csv_export_job;
DROP POLICY IF EXISTS hse_notification_tenant_isolation ON hse_notification;
ALTER TABLE export_template DISABLE ROW LEVEL SECURITY;
ALTER TABLE csv_export_job DISABLE ROW LEVEL SECURITY;
ALTER TABLE hse_notification DISABLE ROW LEVEL SECURITY;
DROP INDEX IF EXISTS idx_export_template_type;
DROP INDEX IF EXISTS idx_csv_export_job_status_requested;
DROP INDEX IF EXISTS idx_hse_notification_inspection;
DROP TABLE IF EXISTS export_template;
DROP TABLE IF EXISTS csv_export_job;
DROP TABLE IF EXISTS hse_notification;
COMMIT;