apiVersion: v1
kind: Namespace
metadata:
  name: cell-system
  labels:
    integin.com/cell-tier: sovereign-core
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
