package robotictrust

import (
	"errors"
	"fmt"
	"regexp"
	"strings"
	"time"
)

// PlatformType identifies the mechanical/locomotion class of the autonomous robot.
type PlatformType string

const (
	PlatformQuadruped PlatformType = "QUADRUPED_CRAWLER" // e.g. Boston Dynamics Spot, ANYmal
	PlatformAerialUAV PlatformType = "AERIAL_UAV"        // Autonomous drone
	PlatformSubseaROV PlatformType = "SUBSEA_ROV"        // Underwater inspection vehicle
	PlatformPipeCrawler PlatformType = "PIPE_CRAWLER"    // NDT internal pipeline crawler
)

var (
	ErrInvalidPlatformType      = errors.New("robotictrust: invalid robot platform type")
	ErrEmptyPlatformID          = errors.New("robotictrust: platform_id cannot be empty")
	ErrEmptyManufacturer        = errors.New("robotictrust: manufacturer cannot be empty")
	ErrInvalidFirmwareDigest    = errors.New("robotictrust: firmware_digest must be 64-character hex SHA-256")
	ErrMissingTPMQuote          = errors.New("robotictrust: missing hardware TPM quote signature")
	ErrUntrustedFirmware        = errors.New("robotictrust: platform firmware digest not in authorized whitelist")
	ErrEnvelopeBreachedAltitude = errors.New("robotictrust: inspection altitude exceeds envelope bounds")
	ErrEnvelopeBreachedVelocity = errors.New("robotictrust: robot velocity exceeds maximum safe envelope")
	ErrEnvelopeEmptyTelemetry   = errors.New("robotictrust: telemetry stream cannot be empty")
	ErrInvalidKeyframeDigest    = errors.New("robotictrust: keyframe digest must be 64-character hex SHA-256")
)

var hexSha256Regex = regexp.MustCompile(`^[a-fA-F0-9]{64}$`)

// RoboticAttestationClaim represents the cryptographic proof generated by the
// robot's internal discrete TPM 2.0 / HSM chip at boot and prior to inspection.
type RoboticAttestationClaim struct {
	PlatformID         string       `json:"platform_id"`
	PlatformType       PlatformType `json:"platform_type"`
	Manufacturer       string       `json:"manufacturer"`
	Model              string       `json:"model"`
	SerialNumber       string       `json:"serial_number"`
	FirmwareDigest     string       `json:"firmware_digest"`      // SHA-256 of verified bootloader + OS
	TPMQuoteSignature  string       `json:"tpm_quote_signature"`  // Hardware signature over PCR registers
	EnclavePublicKey   string       `json:"enclave_public_key"`   // Ed25519 platform key
	AttestationTime    time.Time    `json:"attestation_time"`
	FIPS140_3Level     string       `json:"fips_140_3_level"`     // e.g. "Level 3"
}

func (c RoboticAttestationClaim) Validate() error {
	switch c.PlatformType {
	case PlatformQuadruped, PlatformAerialUAV, PlatformSubseaROV, PlatformPipeCrawler:
	default:
		return ErrInvalidPlatformType
	}
	if strings.TrimSpace(c.PlatformID) == "" {
		return ErrEmptyPlatformID
	}
	if strings.TrimSpace(c.Manufacturer) == "" {
		return ErrEmptyManufacturer
	}
	if !hexSha256Regex.MatchString(c.FirmwareDigest) {
		return ErrInvalidFirmwareDigest
	}
	if strings.TrimSpace(c.TPMQuoteSignature) == "" {
		return ErrMissingTPMQuote
	}
	return nil
}

// SpatialFrameProof records an attested telemetry slice with LiDAR/Photogrammetry hashes.
type SpatialFrameProof struct {
	SequenceNo       uint64    `json:"sequence_no"`
	Timestamp        time.Time `json:"timestamp"`
	AltitudeMeters   float64   `json:"altitude_meters"`
	VelocityMps      float64   `json:"velocity_mps"`
	PointcloudSHA256 string    `json:"pointcloud_sha256"` // Digest of 3D scan data (LAS/PLY)
	KeyframeSHA256   string    `json:"keyframe_sha256"`   // Digest of 4K optical/thermal frame
}

// ExecutionEnvelope establishes the 4D safety boundary within which the autonomous
// robot was permitted to collect statutory inspection evidence.
type ExecutionEnvelope struct {
	MinAltitudeMeters float64  `json:"min_altitude_meters"`
	MaxAltitudeMeters float64  `json:"max_altitude_meters"`
	MaxVelocityMps    float64  `json:"max_velocity_mps"`
	AllowedFirmwares  []string `json:"allowed_firmwares"` // Whitelist of verified firmware hashes
}

// RoboticInspectionReceipt represents the autonomous work packet submitted to the server.
type RoboticInspectionReceipt struct {
	ReceiptID        string                  `json:"receipt_id"`
	WorkOrderID      string                  `json:"work_order_id"`
	AssetDID         string                  `json:"asset_did"`
	TenantID         string                  `json:"tenant_id"`
	OrganizationID   string                  `json:"organization_id"`
	AttestationClaim RoboticAttestationClaim `json:"attestation_claim"`
	Envelope         ExecutionEnvelope       `json:"envelope"`
	TelemetryFrames  []SpatialFrameProof     `json:"telemetry_frames"`
	CompletedAt      time.Time               `json:"completed_at"`
	PayloadDigest    string                  `json:"payload_digest"`
	RobotSignature   string                  `json:"robot_signature"`
}

// ValidateRoboticSubmission executes fail-closed verification of the robot's hardware
// attestation, firmware whitelist, and spatio-temporal execution envelope.
func ValidateRoboticSubmission(receipt RoboticInspectionReceipt) error {
	if err := receipt.AttestationClaim.Validate(); err != nil {
		return fmt.Errorf("attestation validation failed: %w", err)
	}

	// Check firmware against approved envelope whitelist
	if len(receipt.Envelope.AllowedFirmwares) > 0 {
		matched := false
		for _, fw := range receipt.Envelope.AllowedFirmwares {
			if strings.EqualFold(receipt.AttestationClaim.FirmwareDigest, fw) {
				matched = true
				break
			}
		}
		if !matched {
			return fmt.Errorf("%w: firmware %s not authorized", ErrUntrustedFirmware, receipt.AttestationClaim.FirmwareDigest)
		}
	}

	if len(receipt.TelemetryFrames) == 0 {
		return ErrEnvelopeEmptyTelemetry
	}

	// Verify all spatial frames adhere to velocity and altitude safety corridors
	for _, frame := range receipt.TelemetryFrames {
		if !hexSha256Regex.MatchString(frame.KeyframeSHA256) {
			return fmt.Errorf("%w at frame sequence %d", ErrInvalidKeyframeDigest, frame.SequenceNo)
		}
		if frame.AltitudeMeters < receipt.Envelope.MinAltitudeMeters || frame.AltitudeMeters > receipt.Envelope.MaxAltitudeMeters {
			return fmt.Errorf("%w: frame %d altitude %.2fm outside [%.2fm, %.2fm]",
				ErrEnvelopeBreachedAltitude, frame.SequenceNo, frame.AltitudeMeters,
				receipt.Envelope.MinAltitudeMeters, receipt.Envelope.MaxAltitudeMeters)
		}
		if frame.VelocityMps > receipt.Envelope.MaxVelocityMps {
			return fmt.Errorf("%w: frame %d velocity %.2fm/s exceeds max %.2fm/s",
				ErrEnvelopeBreachedVelocity, frame.SequenceNo, frame.VelocityMps, receipt.Envelope.MaxVelocityMps)
		}
	}

	return nil
}
